### ISSUE TITLE
Error Loading Syntax File error after updating to build 3126

### ISSUE THREAD

**Issue by Fuitad** [Medalink/laravel-blade#137]
Here is the error message I get when I try to load any .blade.php file

> Error loading syntax file "Packages/Laravel Blade Highlighter/blade.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

Any idea what's going on and how I can fix it?

**Comment by Fuitad** [comment]
I've been doing some troubleshooting and it seems to be related to two with_prototype blocks

The one that starts on line 51:

```
        - match: '((\s{0}|^)(@)(php)|<\?(?i:php|=)?)(?![^?]*\?>)'
          scope: punctuation.section.embedded.begin.php
          captures:
              0: punctuation.section.embedded.begin.php
              3: constant.other.inline-data.html
              4: entity.name.tag.block.any.html
          push:
            - meta_content_scope: source.php
            - meta_scope: meta.embedded.block.blade.php
            - include: 'scope:source.php'
          with_prototype:
          - match: (?=\?>|(\s{0}|^)(@)(endphp))(\?>|(\s{0}|^)(@)(endphp))
            captures:
              0: punctuation.section.embedded.end.php
              6: constant.other.inline-data.html
              7: entity.name.tag.block.any.html
            pop: true
```

And the one that starts on line 69:

```
        - match: '<\?(?i:php|=)?'
          scope: punctuation.section.embedded.begin.php
          push:
            - meta_content_scope: source.php.blade
            - meta_scope: meta.embedded.line.blade.php
            - include: 'scope:source.php'
          with_prototype:
          - match: (?=\?>)(\?>)
            captures:
              0: punctuation.section.embedded.end.php
            pop: true
```

I'm gonna see if I can figure out the issue and send in a pull request. I've never worked with Sublime plugins before so I'm not sure if/when I can get that done :P. I hope the info I provided will at least help.
